version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./awsontop_usethis.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database from the export you have taken from RDS.
       - db_data:/var/lib/mysqlpersist # To persist database data inside docker storage, occationally you may get issues here. If so just change the location.
     restart: always 
     command: --default-authentication-plugin=mysql_native_password
     
     environment:
       MYSQL_ROOT_PASSWORD: wordpresspwd
       MYSQL_DATABASE: wordpressDB
       MYSQL_USER: wordpressusr
       MYSQL_PASSWORD: wordpresspwd

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always 
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpressusr
       WORDPRESS_DB_PASSWORD: wordpresspwd
       WORDPRESS_DB_NAME: wordpressDB
     volumes:
       - ./var/www/html:/var/www/html
     links:
       - db        
            
volumes:
    db_data: {}